apiVersion: v1
kind: Namespace
metadata:
  name: legacy-automation-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: legacy-mock
  name: legacy-mock
  namespace: legacy-automation-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-mock
  strategy: {}
  template:
    metadata:
      labels:
        app: legacy-mock
        # secret-handshake: "true"
    spec:
      containers:
      - image: kubernetes-is-fun/mock-app:0.1.0
        name: legacy-mock
---
kind: Service
apiVersion: v1
metadata:
  name: legacy-mock-service
  namespace: legacy-automation-demo
spec:
  type: ClusterIP
  selector:
    app: legacy-mock
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legacy-mock-ingress
  namespace: legacy-automation-demo
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  legacy-mock-service
                port:
                  number: 3000
