# permissions for end users to edit frasedeldia.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: frasedeldia-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fdd-controller
    app.kubernetes.io/part-of: fdd-controller
    app.kubernetes.io/managed-by: kustomize
  name: frasedeldia-editor-role
rules:
- apiGroups:
  - apps.kubernetes-is-fun.local
  resources:
  - frasedeldia
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kubernetes-is-fun.local
  resources:
  - frasedeldia/status
  verbs:
  - get
